# Generated by Django 4.2.16 on 2025-07-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('entity_type', models.CharField(choices=[('COMPANY', 'Empresa'), ('FREELANCER', 'Autónomo')], max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bank_name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('irpf_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('invoice_prefix', models.CharField(default='FN', max_length=10)),
                ('current_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('client_type', models.CharField(choices=[('COMPANY', 'Empresa'), ('FREELANCER', 'Autónomo'), ('INDIVIDUAL', 'Particular')], max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('client_tax_id', models.CharField(blank=True, max_length=15)),
                ('client_address', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('irpf_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('PAID', 'Pagada')], default='DRAFT', max_length=20)),
                ('payment_terms', models.TextField(default='Transferencia bancaria')),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/pdfs/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.company')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
            ],
        ),
    ]
