# Generated by Django 4.2.16 on 2025-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_create_default_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(max_length=15),
        ),
    ]
