# Generated by Django 4.2.16 on 2025-07-11 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_alter_company_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('SL', 'Sociedad Limitada'), ('SA', 'Sociedad Anónima'), ('SLU', 'Sociedad Limitada Unipersonal'), ('SCP', 'Sociedad Civil Privada'), ('CB', 'Comunidad de Bienes'), ('AUTONOMO', 'Autónomo')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='mercantile_registry',
            field=models.CharField(blank=True, max_length=200, verbose_name='Registro Mercantil'),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='company',
            name='share_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capital social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_name',
            field=models.CharField(max_length=200, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tipo de IVA por defecto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='iban',
            field=models.CharField(max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_prefix',
            field=models.CharField(default='FN', max_length=10, verbose_name='Prefijo de factura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='irpf_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tipo de IRPF por defecto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(max_length=15, verbose_name='NIF/CIF'),
        ),
    ]
