# Generated by Django 4.2.16 on 2025-07-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_add_legal_compliance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='entity_type',
            field=models.CharField(choices=[('COMPANY', 'Empresa'), ('FREELANCER', 'Autónomo/a')], max_length=20),
        ),
    ]
