# Generated by Django 4.2.16 on 2025-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_migrate_entity_type_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='entity_type',
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_form',
            field=models.CharField(choices=[('AUTONOMO', 'Autónomo/a'), ('SL', 'Sociedad Limitada (SL)'), ('SA', 'Sociedad Anónima (SA)'), ('SLU', 'Sociedad Limitada Unipersonal (SLU)'), ('SCP', 'Sociedad Civil Privada (SCP)'), ('CB', 'Comunidad de Bienes (CB)')], max_length=20, verbose_name='Forma jurídica'),
        ),
    ]
