# Generated by Django 4.2.16 on 2025-07-11 15:05

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_delete_irpfrate_delete_vatrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(verbose_name='Dirección del cliente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_tax_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='NIF/CIF del cliente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_type',
            field=models.CharField(choices=[('COMPANY', 'Empresa'), ('FREELANCER', 'Autónomo'), ('INDIVIDUAL', 'Particular')], max_length=20, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.TextField(default='Transferencia bancaria', verbose_name='Condiciones de pago'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio unitario'),
        ),
    ]
