# Generated by Django 4.2.16 on 2025-07-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_alter_invoice_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('PAID', 'Pagada')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
