# =============================================================================
# ZentoERP Production Deployment Configuration
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Django Multi-tenant Web Service
  # ---------------------------------------------------------------------------
  - type: web
    name: zentoerp-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: production
    
    # Docker commands
    buildCommand: echo "Building Docker image..."
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 3 --worker-class sync --max-requests 1000 --max-requests-jitter 100 --timeout 30 --keep-alive 2 --log-level info --access-logfile - --error-logfile - config.wsgi:application
    preDeployCommand: ./scripts/ultra-safe-migrate.sh
    healthCheckPath: /health/
    autoDeploy: true
    
    # Domain configuration with wildcard DNS
    domains:
      - zentoerp.com
      - "*.zentoerp.com"
      - www.zentoerp.com
    
    # Production environment variables
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: LOAD_TEST_DATA
        value: "False"
      
      # Allowed hosts configuration
      - key: ALLOWED_HOSTS
        value: "zentoerp.com,*.zentoerp.com,www.zentoerp.com,zentoerp-web.onrender.com,*.onrender.com"
      
      # Primary tenant domain
      - key: TENANT_DOMAIN
        value: "zentoerp.com"
      
      # Enable custom domain
      - key: CUSTOM_DOMAIN_ENABLED
        value: "True"
      
      # Security - Auto-generated secure key
      - key: SECRET_KEY
        generateValue: true
      
      # SSL security configuration
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"  # 1 year
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      
      # Database - Secure references to PostgreSQL service
      - key: DATABASE_URL
        fromDatabase:
          name: zentoerp-postgres
          property: connectionString
      - key: DB_NAME
        fromDatabase:
          name: zentoerp-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: zentoerp-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: zentoerp-postgres
          property: password
      - key: DB_HOST
        fromDatabase:
          name: zentoerp-postgres
          property: host
      - key: DB_PORT
        value: "5432"
      
      # Cache configuration
      - key: CACHE_BACKEND
        value: "database"
      
      # Static files configuration
      - key: STATIC_URL
        value: "/static/"
      - key: MEDIA_URL
        value: "/media/"
      - key: STATIC_ROOT
        value: /app/static_collected
      - key: MEDIA_ROOT
        value: /app/media
      
      # Multi-tenant configuration
      - key: TENANT_MODEL
        value: "tenants.Tenant"
      - key: TENANT_DOMAIN_MODEL
        value: "tenants.Domain"
      
      # Logging
      - key: LOG_FILE
        value: /tmp/django.log
      
      # Email configuration
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: noreply@zentoerp.com
