# Generated by Django 4.2.16 on 2025-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_unify_category_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del pago (opcional para períodos sin pago)', max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Fecha de pago (opcional para períodos sin pago)', null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Tarjeta'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('BIZUM', 'Bizum'), ('PAYPAL', 'PayPal'), ('OTHER', 'Otro')], help_text='Método de pago (opcional para períodos sin pago)', max_length=15, null=True, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='status',
            field=models.CharField(choices=[('PERIOD_CREATED', 'Período creado (sin pago)'), ('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PERIOD_CREATED', max_length=15, verbose_name='Estado'),
        ),
    ]
