# Generated by Django 4.2.16 on 2025-06-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_legacy_status'),
        ('accounting', '0007_add_period_created_status'),
    ]

    operations = [
    ]
