# Generated by Django 4.2.16 on 2025-06-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_merge_20250626_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_status',
            field=models.CharField(choices=[('ENABLED', 'Habilitado'), ('DISABLED', 'Deshabilitado administrativamente'), ('SUSPENDED', 'Suspendido temporalmente')], default='ENABLED', max_length=20, verbose_name='Estado administrativo'),
        ),
    ]
