# Generated by Django 4.2.16 on 2025-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_migrate_disabled_to_suspended'),
        ('accounting', '0011_remove_disabled_admin_status'),
    ]

    operations = [
        # Esta migración confirma que el estado DISABLED ha sido completamente removido
        # y que todos los datos han sido migrados correctamente a SUSPENDED
        migrations.AlterField(
            model_name='clientservice',
            name='admin_status',
            field=models.CharField(
                choices=[
                    ('ENABLED', 'Habilitado'), 
                    ('SUSPENDED', 'Suspendido temporalmente')
                ], 
                default='ENABLED', 
                help_text='Control administrativo independiente del estado operacional', 
                max_length=15, 
                verbose_name='Estado administrativo'
            ),
        ),
    ]
