# Generated by Django 4.2.16 on 2025-07-03 08:58

from django.db import migrations, models


def migrate_pending_to_period_created(apps, schema_editor):
    ServicePayment = apps.get_model('accounting', 'ServicePayment')
    ServicePayment.objects.filter(status='PENDING').update(status='PERIOD_CREATED')


def reverse_migrate_pending_to_period_created(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_add_refunded_amount'),
    ]

    operations = [
        migrations.RunPython(
            migrate_pending_to_period_created,
            reverse_migrate_pending_to_period_created,
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='status',
            field=models.CharField(choices=[('PERIOD_CREATED', 'Período creado'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PERIOD_CREATED', max_length=15, verbose_name='Estado'),
        ),
    ]
