# Generated by Django 4.2.16 on 2025-07-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_update_payment_status_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='status',
            field=models.CharField(choices=[('AWAITING_START', 'Periodo creado sin pago'), ('UNPAID_ACTIVE', 'Pendiente de pago'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Reembolsado')], default='AWAITING_START', max_length=15, verbose_name='Estado'),
        ),
    ]
