# Generated by Django 4.2.16 on 2025-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_update_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='remanentes',
            field=models.JSONField(blank=True, default=dict, help_text='Información de remanentes para categoría BUSINESS', verbose_name='Remanentes'),
        ),
    ]
