# Generated by Django 4.2.16 on 2025-07-18 12:07

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(help_text='Nombre completo del profesional', max_length=255, verbose_name='Nombre del nutricionista')),
                ('email', models.EmailField(help_text='Email principal del nutricionista', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('professional_number', models.CharField(blank=True, help_text='Número de colegiado profesional', max_length=50, verbose_name='Número de colegiado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('INACTIVE', 'Inactivo')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, help_text='Define si el tenant puede acceder al sistema', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre el nutricionista', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Nutricionista',
                'verbose_name_plural': 'Nutricionistas',
                'db_table': 'tenants_tenant',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['email'], name='tenants_ten_email_4879df_idx'), models.Index(fields=['status', 'is_active'], name='tenants_ten_status_d181b1_idx'), models.Index(fields=['is_deleted', 'status'], name='tenants_ten_is_dele_5fbd6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
