# Generated by Django 4.2.16 on 2025-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug for tenant identification', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Información adicional sobre el nutricionista', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='professional_number',
            field=models.CharField(blank=True, default='', help_text='Número de colegiado profesional', max_length=50, verbose_name='Número de colegiado'),
        ),
    ]
