# Generated by Django 4.2.16 on 2025-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_client_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created'], 'verbose_name': 'Nutricionista', 'verbose_name_plural': 'Nutricionistas'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, help_text='Información adicional sobre el nutricionista', verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='professional_number',
            field=models.CharField(blank=True, help_text='Número de colegiado profesional', max_length=50, verbose_name='Número de colegiado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('INACTIVE', 'Inactivo')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(help_text='Email principal del nutricionista', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el tenant puede acceder al sistema', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Nombre completo del profesional', max_length=255, verbose_name='Nombre del nutricionista'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(db_index=True, help_text='Identificador único para acceso (ej: maria para maria.tuapp.com)', max_length=50, unique=True, verbose_name='Subdominio'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subdomain'], name='tenants_ten_subdoma_6c6a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['email'], name='tenants_ten_email_4879df_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', 'is_active'], name='tenants_ten_status_d181b1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_deleted', 'status'], name='tenants_ten_is_dele_5fbd6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(check=models.Q(('subdomain__regex', '^[a-z0-9][a-z0-9-]*[a-z0-9]$')), name='tenant_subdomain_format'),
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='tenants_tenant',
        ),
    ]
