# Generated by Django 4.2.16 on 2025-07-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_options_tenant_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='schema_name',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
