# Generated by Django 4.2.16 on 2025-07-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_cleanup_tenant_constraints'),
    ]

    operations = [
    ]
