# Generated by Django 4.2.16 on 2025-07-07 19:43 - Modified to be safe

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_auto_20250707_2143'),
    ]

    operations = [
        # Safe removal of constraints/indices that may not exist
        migrations.RunSQL(
            sql="ALTER TABLE tenants_tenant DROP CONSTRAINT IF EXISTS tenant_subdomain_format;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS tenants_ten_subdoma_6c6a7a_idx;",
            reverse_sql="-- No reverse operation needed"
        ),
        # Ensure the correct constraint exists
        migrations.RunSQL(
            sql="DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenant_slug_format') THEN ALTER TABLE tenants_tenant ADD CONSTRAINT tenant_slug_format CHECK (slug ~ '^[a-z0-9][a-z0-9-]*[a-z0-9]$'); END IF; END $$;",
            reverse_sql="ALTER TABLE tenants_tenant DROP CONSTRAINT IF EXISTS tenant_slug_format;"
        ),
    ]
