# Generated by Django 4.2.16 on 2025-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_final_state_sync'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenant',
            name='tenant_subdomain_format',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenants_ten_subdoma_6c6a7a_idx',
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(check=models.Q(('slug__regex', '^[a-z0-9][a-z0-9-]*[a-z0-9]$')), name='tenant_slug_format'),
        ),
    ]
