# Generated by Django 4.2.16 on 2025-07-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_remove_tenant_tenant_subdomain_format_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenant',
            name='tenant_slug_format',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenants_ten_slug_63daca_idx',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='slug',
        ),
    ]
