# Generated by Django 4.2.16 on 2025-07-18 10:00 - UNIFIED CLEAN MIGRATION
# This migration creates the complete, final state for business_lines app
# SAFE for new databases - ONLY creation operations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # No dependencies - this is the new unified initial migration
    ]

    operations = [
        # Create BusinessLine model with ALL final fields
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Timestamp fields
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                # Business fields
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('parent', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='children', 
                    to='business_lines.businessline', 
                    verbose_name='Línea padre',
                    db_index=True
                )),
                ('level', models.PositiveSmallIntegerField(
                    default=1, 
                    verbose_name='Nivel',
                    help_text='Nivel jerárquico (1-3)'
                )),
                ('is_active', models.BooleanField(
                    default=False, 
                    verbose_name='Activo',
                    db_index=True
                )),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Línea de negocio',
                'verbose_name_plural': 'Líneas de negocio',
                'db_table': 'business_lines',
                'ordering': ['order', 'name'],
            },
        ),
        
        # Add optimized indexes
        migrations.AddIndex(
            model_name='businessline',
            index=models.Index(fields=['parent', 'is_active'], name='business_lines_parent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='businessline',
            index=models.Index(fields=['slug'], name='business_lines_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='businessline',
            index=models.Index(fields=['level', 'order'], name='business_lines_level_order_idx'),
        ),
        
        # Add constraint for unique slug per parent level
        migrations.AddConstraint(
            model_name='businessline',
            constraint=models.UniqueConstraint(
                fields=['slug', 'parent'], 
                name='unique_slug_per_parent'
            ),
        ),
    ]
