# Generated by Django 4.2.16 on 2025-06-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_lines', '0002_unique_slug_per_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessline',
            name='business_line_remanente_field_required',
        ),
        migrations.RemoveField(
            model_name='businessline',
            name='has_remanente',
        ),
        migrations.RemoveField(
            model_name='businessline',
            name='remanente_field',
        ),
        migrations.AddField(
            model_name='businessline',
            name='allows_remanentes',
            field=models.BooleanField(default=False, help_text='Indica si esta línea de negocio puede tener remanentes configurados', verbose_name='Permite remanentes'),
        ),
    ]
