# Generated by Django 4.2.16 on 2025-06-29 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_disabled_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_lines', '0003_create_flexible_remanentes_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemanenteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de remanente')),
                ('description', models.TextField(blank=True, help_text='Descripción del propósito de este tipo de remanente', verbose_name='Descripción')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto por defecto (puede ser positivo o negativo)', max_digits=10, null=True, verbose_name='Monto por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tipo de Remanente',
                'verbose_name_plural': 'Tipos de Remanente',
                'db_table': 'remanente_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePeriodRemanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del remanente (puede ser positivo o negativo)', max_digits=10, verbose_name='Monto')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre este remanente', verbose_name='Notas')),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_remanentes', to='accounting.clientservice', verbose_name='Servicio del cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('remanente_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_lines.remanentetype', verbose_name='Tipo de remanente')),
            ],
            options={
                'verbose_name': 'Remanente de Período',
                'verbose_name_plural': 'Remanentes de Período',
                'db_table': 'service_period_remanentes',
                'ordering': ['-period_start', 'remanente_type__name'],
                'unique_together': {('client_service', 'period_start', 'period_end', 'remanente_type')},
            },
        ),
        migrations.CreateModel(
            name='BusinessLineRemanenteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_enabled', models.BooleanField(default=True, help_text='Si este tipo de remanente está habilitado para esta línea de negocio', verbose_name='Habilitado')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto por defecto específico para esta línea de negocio (sobrescribe el del tipo)', max_digits=10, null=True, verbose_name='Monto por defecto específico')),
                ('business_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanente_configs', to='business_lines.businessline', verbose_name='Línea de negocio')),
                ('remanente_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_lines.remanentetype', verbose_name='Tipo de remanente')),
            ],
            options={
                'verbose_name': 'Configuración de Remanente por Línea',
                'verbose_name_plural': 'Configuraciones de Remanente por Línea',
                'db_table': 'business_line_remanente_configs',
                'ordering': ['business_line__name', 'remanente_type__name'],
                'unique_together': {('business_line', 'remanente_type')},
            },
        ),
    ]
