# Generated by Django 4.2.16 on 2025-06-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_lines', '0004_add_remanente_models'),
    ]

    operations = [
        # Eliminar las tablas de remanentes
        migrations.DeleteModel(
            name='ServicePeriodRemanente',
        ),
        migrations.DeleteModel(
            name='BusinessLineRemanenteConfig',
        ),
        migrations.DeleteModel(
            name='RemanenteType',
        ),
    ]
