# Generated by Django 4.2.16 on 2025-06-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_lines', '0005_remove_remanente_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessline',
            name='allows_remanentes',
        ),
    ]
