# Generated by Django 4.2.16 on 2025-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_lines', '0006_remove_allows_remanentes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessline',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Activo'),
        ),
    ]
