# Generated by Django 4.2.16 on 2025-07-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_migrate_invoice_data_to_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='default_vat_rate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='irpf_rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='irpf_rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat_rate',
        ),
    ]
