# Generated by Django 4.2.16 on 2025-07-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_alter_invoiceitem_irpf_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IRPFRate',
        ),
        migrations.DeleteModel(
            name='VATRate',
        ),
    ]
