# Generated by Django 4.2.16 on 2025-06-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('dni', models.CharField(help_text='Documento de identidad único', max_length=20, unique=True, verbose_name='DNI/NIE')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre el cliente', verbose_name='Notas')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('category', models.CharField(choices=[('WHITE', 'Blanco'), ('BLACK', 'Negro')], max_length=10, verbose_name='Categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('payment_method', models.CharField(choices=[('CARD', 'Tarjeta'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('BIZUM', 'Bizum')], max_length=15, verbose_name='Método de pago')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Fecha de renovación')),
                ('remanentes', models.JSONField(blank=True, default=dict, help_text='Información de remanentes para categoría BLACK', verbose_name='Remanentes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('business_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='business_lines.businessline', verbose_name='Línea de negocio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounting.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Servicio de cliente',
                'verbose_name_plural': 'Servicios de clientes',
                'db_table': 'client_services',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['dni'], name='clients_dni_fc9f79_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active', 'full_name'], name='clients_is_acti_e5cf1e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['client', 'is_active'], name='client_serv_client__815139_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['business_line', 'category'], name='client_serv_busines_d6c053_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['start_date'], name='client_serv_start_d_171a32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together={('client', 'business_line', 'category')},
        ),
    ]
