# Generated by Django 4.2.16 on 2025-06-23 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=15, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CARD', 'Tarjeta'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('BIZUM', 'Bizum'), ('PAYPAL', 'PayPal'), ('OTHER', 'Otro')], max_length=15, verbose_name='Método de pago')),
                ('reference_number', models.CharField(blank=True, help_text='Referencia de la transacción', max_length=100, verbose_name='Número de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Pago de servicio',
                'verbose_name_plural': 'Pagos de servicios',
                'db_table': 'service_payments',
                'ordering': ['-payment_date', '-created'],
            },
        ),
        migrations.RemoveIndex(
            model_name='clientservice',
            name='client_serv_start_d_171a32_idx',
        ),
        migrations.RemoveField(
            model_name='clientservice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='clientservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='clientservice',
            name='renewal_date',
        ),
        migrations.RemoveField(
            model_name='clientservice',
            name='start_date',
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='client_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.clientservice', verbose_name='Servicio'),
        ),
        migrations.AddIndex(
            model_name='servicepayment',
            index=models.Index(fields=['client_service', 'status'], name='service_pay_client__cdcd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepayment',
            index=models.Index(fields=['payment_date'], name='service_pay_payment_3ffc00_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepayment',
            index=models.Index(fields=['period_start', 'period_end'], name='service_pay_period__fe7dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepayment',
            index=models.Index(fields=['status', 'payment_date'], name='service_pay_status_647630_idx'),
        ),
    ]
