# Generated by Django 4.2.16 on 2025-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_servicepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='notes',
            field=models.TextField(blank=True, help_text='Observaciones específicas del servicio', verbose_name='Notas del servicio'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio base'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='service_type',
            field=models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual'), ('CUSTOM', 'Personalizado')], default='MONTHLY', max_length=20, verbose_name='Tipo de servicio'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('SUSPENDED', 'Suspendido'), ('EXPIRED', 'Expirado')], default='INACTIVE', max_length=15, verbose_name='Estado del servicio'),
        ),
    ]
