# Generated by Django 4.2.16 on 2025-06-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_clientservice_end_date_clientservice_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservice',
            name='service_type',
        ),
    ]
