# Generated by Django 4.2.16 on 2025-06-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_service_type_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['client', 'business_line', 'category', 'created'], name='client_serv_client__2561e8_idx'),
        ),
    ]
