# Generated by Django 4.2.16 on 2025-06-25 19:52

from django.db import migrations, models


def convert_categories_to_lowercase(apps, schema_editor):
    ClientService = apps.get_model('accounting', 'ClientService')
    ClientService.objects.filter(category='WHITE').update(category='white')
    ClientService.objects.filter(category='BLACK').update(category='black')


def reverse_convert_categories(apps, schema_editor):
    ClientService = apps.get_model('accounting', 'ClientService')
    ClientService.objects.filter(category='white').update(category='WHITE')
    ClientService.objects.filter(category='black').update(category='BLACK')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(convert_categories_to_lowercase, reverse_convert_categories),
        migrations.AlterField(
            model_name='clientservice',
            name='category',
            field=models.CharField(choices=[('white', 'Blanco'), ('black', 'Negro')], max_length=10, verbose_name='Categoría'),
        ),
    ]
