# Generated by Django 4.2.16 on 2025-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_merge_20250626_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='admin_status',
            field=models.CharField(choices=[('ENABLED', 'Habilitado'), ('SUSPENDED', 'Suspendido temporalmente'), ('DISABLED', 'Deshabilitado administrativamente')], default='ENABLED', help_text='Control administrativo independiente del estado operacional', max_length=15, verbose_name='Estado administrativo'),
        ),
    ]
