# Generated by Django 4.2.16 on 2025-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_clientservice_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='category',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=10, verbose_name='Categoría'),
        ),
    ]
