# Generated by Django 4.2.16 on 2025-06-29 10:44

from django.db import migrations


def migrate_disabled_to_suspended(apps, schema_editor):
    """Migra servicios con admin_status 'DISABLED' a 'SUSPENDED'"""
    ClientService = apps.get_model('accounting', 'ClientService')
    
    # Buscar servicios con estado DISABLED y cambiarlos a SUSPENDED
    updated_count = ClientService.objects.filter(admin_status='DISABLED').update(admin_status='SUSPENDED')
    
    if updated_count > 0:
        print(f"Migrados {updated_count} servicios de DISABLED a SUSPENDED")


def reverse_migration(apps, schema_editor):
    """Migración reversa: cambiar SUSPENDED de vuelta a DISABLED"""
    ClientService = apps.get_model('accounting', 'ClientService')
    
    # Solo revertir si había servicios DISABLED originalmente
    updated_count = ClientService.objects.filter(admin_status='SUSPENDED').update(admin_status='DISABLED')
    
    if updated_count > 0:
        print(f"Revertidos {updated_count} servicios de SUSPENDED a DISABLED")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_clientservice_category'),
    ]

    operations = [
        migrations.RunPython(
            migrate_disabled_to_suspended,
            reverse_migration,
        ),
    ]
