# Generated by Django 4.2.16 on 2025-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_clientservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='admin_status',
            field=models.CharField(choices=[('ENABLED', 'Habilitado'), ('SUSPENDED', 'Suspendido temporalmente')], default='ENABLED', help_text='Control administrativo independiente del estado operacional', max_length=15, verbose_name='Estado administrativo'),
        ),
    ]
