# Generated by Django 4.2.16 on 2025-06-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_disabled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='remanente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de remanente aplicado (positivo o negativo)', max_digits=10, null=True, verbose_name='Remanente'),
        ),
    ]
