# Generated by Django 4.2.16 on 2025-06-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_add_remanente_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad reembolsada del pago original', max_digits=10, verbose_name='Monto reembolsado'),
        ),
    ]
