# Generated by Django 4.2.16 on 2025-07-15 09:19

from django.db import migrations, models


def update_category_values(apps, schema_editor):
    ClientService = apps.get_model('accounting', 'ClientService')
    ClientService.objects.filter(category='white').update(category='personal')
    ClientService.objects.filter(category='black').update(category='business')


def reverse_category_values(apps, schema_editor):
    ClientService = apps.get_model('accounting', 'ClientService')
    ClientService.objects.filter(category='personal').update(category='white')
    ClientService.objects.filter(category='business').update(category='black')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_remove_cancelled_status'),
    ]

    operations = [
        migrations.RunPython(
            update_category_values,
            reverse_category_values,
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=10, verbose_name='Categoría'),
        ),
    ]
