# Generated by Django 4.2.16 on 2025-07-15 19:13

from django.db import migrations


def migrate_legacy_categories(apps, schema_editor):
    ClientService = apps.get_model('accounting', 'ClientService')
    ClientService.objects.filter(category='white').update(category='personal')
    ClientService.objects.filter(category='black').update(category='business')


def reverse_migrate_legacy_categories(apps, schema_editor):
    ClientService = apps.get_model('accounting', 'ClientService')
    ClientService.objects.filter(category='personal').update(category='white')
    ClientService.objects.filter(category='business').update(category='black')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_clientservice_remanentes'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_categories, reverse_migrate_legacy_categories),
    ]
