#!/bin/bash

# =============================================================================
# render-webservice-config.sh - Configuración del Web Service en Render
# =============================================================================
# Guía paso a paso para configurar ZentoERP en Render

set -e

echo "🚀 Configuración del Web Service ZentoERP en Render"
echo "=================================================="

echo ""
echo "📋 CONFIGURACIÓN BÁSICA:"
echo "------------------------"
echo "Repository: https://github.com/gmartincor/zento_erp"
echo "Branch: production"
echo "Service Name: zentoerp-web"
echo "Environment: Web Service"

echo ""
echo "🐳 CONFIGURACIÓN DOCKER:"
echo "------------------------"
echo "✅ Use Docker: YES"
echo "Dockerfile Path: Dockerfile"
echo "Docker Context: . (root)"
echo "Docker Command: (usar el CMD del Dockerfile)"

echo ""
echo "⚙️  CONFIGURACIÓN DE BUILD:"
echo "---------------------------"
echo "Build Command:"
echo "  ./scripts/render-deploy.sh"
echo ""
echo "Start Command:"
echo "  gunicorn --bind 0.0.0.0:\$PORT --workers 3 --worker-class sync --max-requests 1000 --max-requests-jitter 100 --timeout 30 --keep-alive 2 --log-level info --access-logfile - --error-logfile - config.wsgi:application"

echo ""
echo "🔧 VARIABLES DE ENTORNO REQUERIDAS:"
echo "-----------------------------------"

echo ""
echo "# 🔐 Django Configuration"
echo "DJANGO_SETTINGS_MODULE=config.settings.production"
echo "DEBUG=False"
echo "ALLOWED_HOSTS=zentoerp.com,*.zentoerp.com,zentoerp-web.onrender.com"

echo ""
echo "# 🔑 Security"
echo "SECRET_KEY=[GENERAR_CLAVE_SEGURA]"

echo ""
echo "# 🗄️  Database (PostgreSQL)"
echo "DATABASE_URL=postgresql://usuario:password@host:puerto/database"
echo "DB_NAME=tu_database_name"
echo "DB_USER=tu_database_user"
echo "DB_PASSWORD=tu_database_password"
echo "DB_HOST=tu_database_host"
echo "DB_PORT=5432"

echo ""
echo "# 🚀 Cache Configuration (sin Redis)"
echo "CACHE_BACKEND=database"

echo ""
echo "# 📁 Static Files"
echo "STATIC_URL=/static/"
echo "MEDIA_URL=/media/"

echo ""
echo "# 🌐 Multi-tenant Configuration"
echo "TENANT_MODEL=tenants.Client"
echo "TENANT_DOMAIN_MODEL=tenants.Domain"

echo ""
echo "🔑 GENERAR SECRET_KEY SEGURA:"
echo "-----------------------------"
echo "Usar el siguiente comando para generar una clave segura:"
echo ""
echo "python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""

echo ""
echo "🏗️  PASOS DE CONFIGURACIÓN:"
echo "---------------------------"
echo "1. ✅ Crear Web Service en Render"
echo "2. ✅ Conectar repositorio: gmartincor/zento_erp"
echo "3. ✅ Seleccionar rama: production"
echo "4. ✅ Habilitar Docker"
echo "5. ✅ Configurar variables de entorno"
echo "6. ✅ Hacer primer deploy"
echo "7. ✅ Configurar dominio personalizado"
echo "8. ✅ Configurar DNS"
echo "9. ✅ Probar multi-tenant"

echo ""
echo "🌐 CONFIGURACIÓN DE DOMINIO:"
echo "----------------------------"
echo "Después del primer deploy exitoso:"
echo "• Ir a Settings > Custom Domains"
echo "• Agregar: zentoerp.com"
echo "• Agregar: *.zentoerp.com (wildcard)"
echo "• Verificar DNS configuration"
echo "• Activar SSL automático"

echo ""
echo "🔍 VERIFICACIÓN POST-DEPLOY:"
echo "----------------------------"
echo "• https://zentoerp-web.onrender.com (URL temporal)"
echo "• https://zentoerp.com (dominio principal)"
echo "• https://demo.zentoerp.com (ejemplo multi-tenant)"
echo "• /admin/ (panel de administración)"
echo "• /health/ (health check)"

echo ""
echo "📊 CONFIGURACIÓN RECOMENDADA:"
echo "-----------------------------"
echo "Plan: Starter ($7/mes) o Professional ($25/mes)"
echo "Recursos: 512MB RAM, 0.5 CPU (Starter)"
echo "Auto-deploy: Habilitado en rama production"
echo "Health Check: /health/"

echo ""
echo "🚨 CHECKLIST PREVIO AL DEPLOY:"
echo "------------------------------"
echo "□ PostgreSQL database creado y configurado"
echo "□ Variables de entorno configuradas"
echo "□ SECRET_KEY generada y configurada"
echo "□ ALLOWED_HOSTS actualizado"
echo "□ Docker habilitado"
echo "□ Repositorio y rama correctos"

echo ""
echo "💡 TROUBLESHOOTING:"
echo "------------------"
echo "• Logs: Dashboard > Logs en Render"
echo "• Build failed: Verificar scripts/render-deploy.sh"
echo "• Database connection: Verificar DATABASE_URL"
echo "• Static files: Verificar STATIC_URL y collectstatic"
echo "• Multi-tenant: Verificar ALLOWED_HOSTS con wildcards"

echo ""
echo "📝 SIGUIENTE PASO:"
echo "-----------------"
echo "1. Completa la configuración del Web Service"
echo "2. Haz el primer deploy"
echo "3. Configura el dominio personalizado"
echo "4. Ejecuta: ./scripts/dns-config.sh"

echo ""
echo "🎯 ¡LISTO PARA DEPLOY!"
echo "====================="
