def configure_tenant_settings():
    return {
        'SHARED_APPS': [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'apps.core',
            'apps.tenants',
        ],
        'TENANT_APPS': [
            'apps.authentication',
            'apps.dashboard', 
            'apps.accounting',
            'apps.business_lines',
            'apps.expenses',
        ],
        'INSTALLED_APPS': [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'apps.core',
            'apps.tenants',
            'apps.authentication',
            'apps.dashboard', 
            'apps.accounting',
            'apps.business_lines',
            'apps.expenses',
        ],
    }
