# Generated by Django 4.2.16 on 2025-07-18 12:08

import apps.expenses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category_type', models.CharField(choices=[('FIXED', 'Fijo'), ('VARIABLE', 'Variable'), ('TAX', 'Impuesto'), ('OCCASIONAL', 'Puntual')], max_length=20, verbose_name='Tipo de categoría')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gastos',
                'db_table': 'expense_categories',
                'ordering': ['category_type', 'name'],
                'indexes': [models.Index(fields=['category_type', 'is_active'], name='expense_cat_categor_b516e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('service_category', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='business', max_length=10, verbose_name='Categoría de Servicio')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('accounting_year', models.PositiveIntegerField(db_index=True, verbose_name='Año contable')),
                ('accounting_month', models.PositiveSmallIntegerField(db_index=True, verbose_name='Mes contable')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Número de factura')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.expenses.models.expense_attachment_path, verbose_name='Archivo adjunto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'expenses',
                'ordering': ['-date', '-created'],
                'indexes': [models.Index(fields=['accounting_year', 'accounting_month'], name='expenses_account_193753_idx'), models.Index(fields=['category', 'date'], name='expenses_categor_99cf21_idx'), models.Index(fields=['date'], name='expenses_date_a77b87_idx'), models.Index(fields=['accounting_year', 'category'], name='expenses_account_c7338d_idx'), models.Index(fields=['service_category', 'date'], name='expenses_service_7fd0d9_idx')],
            },
        ),
    ]
