# Generated by Django 4.2.22 on 2025-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción opcional de la categoría', verbose_name='Descripción'),
        ),
    ]
