# Generated by Django 4.2.16 on 2025-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_add_description_to_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='service_category',
            field=models.CharField(
                choices=[
                    ('personal', 'Personal'),
                    ('business', 'Business')
                ],
                default='business',
                max_length=10,
                verbose_name='Categoría de Servicio'
            ),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['service_category', 'date'], name='expenses_service_cat_idx'),
        ),
    ]
