# Generated by Django 4.2.16 on 2025-07-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_add_service_category_to_expense'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_service_7fd0d9_idx',
            old_name='expenses_service_cat_idx',
        ),
    ]
