# Generated by Django 4.2.16 on 2025-07-15 14:07

import apps.expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_expenses_service_cat_idx_expenses_service_7fd0d9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.expenses.models.expense_attachment_path, verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
