# Generated by Django 4.2.16 on 2025-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GLOW_VIEWER', 'Visualizador Glow')], default='GLOW_VIEWER', max_length=20, verbose_name='Rol'),
        ),
    ]
