# Generated by Django 4.2.16 on 2025-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_lines',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AUTONOMO', 'Autónomo')], default='AUTONOMO', max_length=20, verbose_name='Rol'),
        ),
    ]
