# Generated by Django 4.2.16 on 2025-07-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_remove_slug_field'),
        ('authentication', '0003_remove_user_business_lines_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='tenants.tenant', verbose_name='Tenant asociado'),
        ),
    ]
