# Generated by Django 4.2.16 on 2025-07-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_tenant_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
